### ISSUE TITLE
saving OptimalBinning & some other issues

### ISSUE THREAD

**Issue by similang** [guillermo-navas-palencia/optbinning#77] opened 2021-02-05 13:03 UTC
Hi, 

I am dealing with a big dataset => so scorecard module can't be used on my pc. I resort to OptimalBinning of each variable: 

**Code**
optb = OptimalBinning(name=variable, dtype="numerical")
optb.fit(x, y)

import joblib
joblib.dump(optb, output+'txt.pkl')

**Error**
_TypeError: can't pickle _thread.RLock objects_

Would love to: 
1. Obtain the criteria of bins (to transform the dataset later)? Or;
2. Save the OptimalBinning in pickle format.

Any thoughts on the above are much appreciated.

**Comment by guillermo-navas-palencia** [comment] 2021-02-05 15:50
Hi @similang,

I just test this and I did not have any problem:

![image](https://user-images.githubusercontent.com/40094942/107056033-32eb3300-67d2-11eb-9cee-4619735717ce.png)

Tested in Linux Lubuntu with Python 3.7.

**Comment by guillermo-navas-palencia** [comment] 2021-02-05 16:14
I searched for this issue with joblib, and it seems to be related to multiprocessing. Are you trying to run several OptimalBinning in parallel?

**Comment by similang** [comment] 2021-02-05 18:51
Ah, no - just a for loop and I don't apply any multiprocessing. Even for one variable the same problem persists. 

I am doing it in a windows pc. By the way - is it possible to get the bin rules to apply on new datasets?

**Comment by guillermo-navas-palencia** [comment] 2021-02-05 18:56
Not directly, but you can retrieve the split points for each variable and implement your own transform method.

**Comment by guillermo-navas-palencia** [comment] 2021-02-05 19:19
I will add new functionality to create a binning_process/scorecard from a set of OptimalBinning objects. In this way, it will be possible to transform and create a scorecard table for large datasets while only keeping the data x and target y in memory. Does it sound reasonable?

**Comment by similang** [comment] 2021-02-05 19:46
That would be perfect.

**Comment by guillermo-navas-palencia** [comment] 2021-02-05 19:48
Perfect, it might take a few days. I will keep you informed.

**Comment by naenumtou** [comment] 2021-02-08 13:25
@guillermo-navas-palencia Having the same issue for exporting the object and looking forward to seeing the new support. However, why did you successfully run without any issue?

**Comment by guillermo-navas-palencia** [comment] 2021-02-08 18:37
Hi @naenumtou, are you using Windows, Linux or Mac? I only tested it on Linux.

**Comment by naenumtou** [comment] 2021-02-09 01:49
@guillermo-navas-palencia I am using on Google Colab.

**Comment by guillermo-navas-palencia** [comment] 2021-02-09 12:48
I can reproduce the error on Google Colab. However, I run it without any issue on Linux and Windows using anaconda 3.7 y 3.8. I would recommend you to run it locally and see if the error persists. I do not know why it does not work on Google Colab, I do not use it regularly.

**Comment by similang** [comment] 2021-02-09 16:59
Hi, is there .whl for this package? Tried to install with .whl.

**Comment by guillermo-navas-palencia** [comment] 2021-02-09 17:32
https://pypi.org/project/optbinning/0.9.0/#files

**Comment by guillermo-navas-palencia** [comment] 2021-02-12 18:37
Hi,

I found the source of the error. The logger in all OptBinning classes cannot be pickled and Google Colab fails. It will be fixed in the next release. In addition, all optimal binning classes will expose the method save to automatically save the object to a pickle file.

**Comment by guillermo-navas-palencia** [comment] 2021-02-14 12:31
Hi @similang @naenumtou,

Release 0.9.1 is ready. It has been tested on Google Colab installed with the wheel (https://pypi.org/project/optbinning/#files). Please update OptBinning and reopen this issue if you encounter any problem.

**Closed by guillermo-navas-palencia** 2021-02-14 12:31 UTC
Labels: enhancement

**Comment by naenumtou** [comment] 2021-02-21 14:48
@guillermo-navas-palencia I have tried to install via wheel on my Colab environment. It fail to build because the library required python version >=3.7 but on Colab is 3.6.9.

Is there any way to fix it?

**Comment by guillermo-navas-palencia** [comment] 2021-02-21 17:24
Hi @naenumtou,

When I tested it on Colab I created a wheel changing the requirement >= 3.7 in setup.py manually. Python 3.7 is required due to some dependencies with CVXPY (SCS solver) but apparently, it might work with Python 3.6 under some environments. I would recommend updating Colab python to 3.7 if possible (python 3.6 is from 2016). Otherwise, try to run it locally.

It might help: https://stackoverflow.com/questions/63867581/install-python-3-7-via-google-colab-as-default-python

**Comment by apatange-source** [comment] 2021-09-07 07:24
> Hi @similang @naenumtou,
> 
> Release 0.9.1 is ready. It has been tested on Google Colab installed with the wheel (https://pypi.org/project/optbinning/#files). Please update OptBinning and reopen this issue if you encounter any problem.

Hey! I'm still getting the same issue saying:
TypeError: cannot pickle '_thread.lock' object

I'm running python 3.8 wiht optbinning 0.12.0
