### ISSUE TITLE
OptimalBinning2D not working with numerical and categorical predictor

### ISSUE THREAD

**Issue by detrin** [guillermo-navas-palencia/optbinning#197] opened 2022-10-03 18:10 UTC
Hello, I enjoy your package very much as it makes feature engineering, in some cases, much simpler.
I suspect it is a bug, and you probably didn't think of 2D binning using categorical predictors. I cannot provide you the data, but I hope it is clear.

```python
from optbinning import OptimalBinning2D

col1, col2 = "NUMERICAL_32", "CATEGORICAL_10"
col_target = "TARGET"
optb = OptimalBinning2D(name_x=col1, name_y=col2, dtype_x="numerical", dtype_y="categorical", solver="cp")
x = data[col1].values
y = data[col2].values
z = data[col_target]
optb.fit(x, y, z)
optb.binning_table.build(show_bin_xy=True)
ifeat_woe = optb.transform(x, y, metric="woe")
```
I am getting following error.
```
Traceback (most recent call last):
  File "/Users/danielherman/Documents/projects/ifeat/ifeat_optbinning.py", line 43, in <module>
    ifeat_woe = optb.transform(x, y, metric="woe")
  File "/Users/danielherman/Documents/projects/ifeat/env/lib/python3.9/site-packages/optbinning/binning/multidimensional/binning_2d.py", line 551, in transform
    return transform_binary_target(
  File "/Users/danielherman/Documents/projects/ifeat/env/lib/python3.9/site-packages/optbinning/binning/multidimensional/transformations_2d.py", line 123, in transform_binary_target
    bins_str = bin_xy_str_format(dtype_x, dtype_y, splits_x, splits_y,
  File "/Users/danielherman/Documents/projects/ifeat/env/lib/python3.9/site-packages/optbinning/binning/multidimensional/binning_statistics_2d.py", line 72, in bin_xy_str_format
    _by = _bin_fmt_categorical(by, categories_y)
  File "/Users/danielherman/Documents/projects/ifeat/env/lib/python3.9/site-packages/optbinning/binning/multidimensional/binning_statistics_2d.py", line 42, in _bin_fmt_categorical
    n_categories = len(categories)
TypeError: object of type 'NoneType' has no len()
```
I am also using the last available version 0.15.1.

Will you add the support of 2D binning with numerical+categorical predictors and categorical+categorical predictors?

**Comment by guillermo-navas-palencia** [comment] 2022-10-03 18:29
This feature is already supported since version 0.15.0: http://gnpalencia.org/optbinning/tutorials/tutorial_binning_2d.html#Categorical-variables. Could you check if not passing show_bin_xy can solve the issue? I would need the data to reproduce this issue since using my datasets this error does not occur.

**Comment by detrin** [comment] 2022-10-03 19:11
It didn't solve the issue, I will try to build reproducible code today.

**Comment by detrin** [comment] 2022-10-03 19:44
Okay, hope this helps.

```python
# %%
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import optbinning
import random

# %%
values1 = []
for i in range(5000):
    t_prob = np.random.uniform(0, 1)
    x1 = t_prob + np.random.normal(loc=0., scale=0.2)
    x2 = "A"
    t = random.choices(population=[0, 1], weights=[1-t_prob, t_prob], k=1)[0]
    values1.append([x1, x2, t_prob, t])

values2 = []
for i in range(5000):
    t_prob = np.random.uniform(0, 1)
    x1 = 1-t_prob + np.random.normal(loc=0., scale=0.2)
    x2 = "B"
    t = random.choices(population=[0, 1], weights=[1-t_prob, t_prob], k=1)[0]
    values2.append([x1, x2, t_prob, t])

data = pd.DataFrame(values1 + values2, columns=["x1", "x2", "t_prob", "t"])

# %%
from optbinning import OptimalBinning2D

col1, col2 = "x1", "x2"
col_target = "t"
optb = OptimalBinning2D(name_x=col1, name_y=col2, dtype_x="numerical", dtype_y="categorical", solver="cp")
x = data[col1].values
y = data[col2].values
z = data[col_target]
optb.fit(x, y, z)

# %%
optb.binning_table.build()


ifeat_woe = optb.transform(x, y, metric="woe")


# %%

```
absl-py==1.2.0
appnope==0.1.3
asttokens==2.0.8
backcall==0.2.0
contourpy==1.0.5
cvxpy==1.2.1
cycler==0.11.0
debugpy==1.6.3
decorator==5.1.1
ecos==2.0.10
entrypoints==0.4
executing==1.1.0
fonttools==4.37.4
ipykernel==6.16.0
ipython==8.5.0
jedi==0.18.1
joblib==1.2.0
jupyter-core==4.11.1
jupyter_client==7.3.5
kiwisolver==1.4.4
matplotlib==3.6.0
matplotlib-inline==0.1.6
mypy==0.982
mypy-extensions==0.4.3
nest-asyncio==1.5.6
numpy==1.23.3
optbinning==0.15.1
ortools==9.4.1874
osqp==0.6.2.post5
packaging==21.3
pandas==1.5.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.2.0
prompt-toolkit==3.0.31
protobuf==4.21.7
psutil==5.9.2
ptyprocess==0.7.0
pure-eval==0.2.2
pybind11==2.10.0
Pygments==2.13.0
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2022.4
pyzmq==24.0.1
qdldl==0.1.5.post2
ropwr==0.3.0
scikit-learn==1.1.2
scipy==1.9.1
scs==3.2.0
six==1.16.0
stack-data==0.5.1
threadpoolctl==3.1.0
tomli==2.0.1
tornado==6.2
traitlets==5.4.0
typing_extensions==4.3.0
wcwidth==0.2.5
```

**Comment by guillermo-navas-palencia** [comment] 2022-10-03 23:08
Hi @detrin. Apologies, the 2D transform method was not prepared for categorical variables. See commit in develop branch. This bug fix will be part of the oncoming release 0.16.0. Thanks for your contribution.

**Comment by detrin** [comment] 2022-10-04 06:47
Hi @guillermo-navas-palencia, really thank you for fixing it so quickly! I will be using the version from that commit from now on.

**Comment by guillermo-navas-palencia** [comment] 2022-10-04 07:33
Perfect. The code must be improved, though.

**Closed** 2022-10-13 16:35 UTC
Labels: bug
